<?php

namespace AiosInitialSetup\App\Modules\ComingSoonGenerator;

class Module
{
  /**
   * Module constructor.
   */
  public function __construct()
  {
    add_action('admin_enqueue_scripts', [$this, 'module_resources']);
    add_action('add_meta_boxes', [$this, 'settings_post']);
    add_action('wp_ajax_generate_cs_content', [$this, 'aios_generate_cs_content']);
    add_action('wp_ajax_nopriv_generate_cs_content', [$this, 'aios_generate_cs_content']);
  }

  public function module_resources()
  {
    wp_enqueue_script('page-settings-script', plugin_dir_url(__FILE__) . '/page-settings-script.js');
    wp_localize_script('page-settings-script', 'ajaxurl', admin_url('admin-ajax.php'));
  }

  public function settings_post()
  {
    add_meta_box('wp_settings_view', 'Page Settings', [$this, 'settings_post_function'], 'page', 'side', 'high');
    add_meta_box('wp_settings_view', 'Page Settings', [$this, 'settings_post_function'], 'post', 'side', 'high');
  }

  public function settings_post_function($post)
  {
    wp_nonce_field('wp_settings_view', 'wp_settings_view_nonce', true, true);
    ?>
    <div class="metabox-holder">
      <div class="metabox-row">
        <div class="btn-holder">
          <a style="width: 100%; text-align: center;" href="javascript:;" class="cs-generate-btn button">Generate
            Placeholder Content</a>
        </div>
      </div>
    </div>
    <?php
  }

  public function aios_generate_cs_content()
  {
    $output = '<strong>Thank you for visiting ' . get_bloginfo('title') . '!</strong>
<p>We have scheduled an update for this section of the website, and invite you to come back at a later date to view our new content.</p>';
    $cf7_query = new \WP_Query(['post_type' => 'wpcf7_contact_form', 's' => 'Contact Us (Auto-generated by AIOS Initial Setup)']);
    $cf7_query = array_filter($cf7_query->posts);

    if (!empty($cf7_query)) {
      $output .= '

<p>From here, feel free to go back to our <a href="[blogurl]"><strong>Homepage</strong></a>, or send us any inquiries you may have and we\'ll get right back in touch.</p>

<div class="aidefcf-wrapper aidefcf-wrapper-contact-us-(auto-generated-by-aios-initial-setup)">[contact-form-7 id="' . $cf7_query[0]->ID . '" title="Contact Us (Auto-generated by AIOS Initial Setup)" html_class="use-floating-validation-tip"]</div>';
    } else {
      $output .= '
<p>From here, feel free to go back to our <a href="[blogurl]"><strong>Homepage</strong></a>.</p>';
    }

    echo json_encode($output);
    wp_die();
  }
}

new Module();
