<form method="post">
	<div class="wpui-row wpui-row-box">
		<div class="wpui-col-md-3">
			<p><span class="wpui-settings-title">Generate Pages</span> Please <strong>uncheck</strong> the field if you don't want to generate a contact for that Page.</p>
		</div>
		<div class="wpui-col-md-9">
			<div class="form-group">
				<div class="form-checkbox-group">
					<div class="form-checkbox">
						<label><input type="checkbox" class="generate-default-pages" value="what-is-my-home-worth" checked> What is My Home Worth</label>
					</div>
					<div class="form-checkbox">
						<label><input type="checkbox" class="generate-default-pages" value="find-my-dream-home" checked> Find My Dream Home</label>
					</div>
					<div class="form-checkbox">
						<label><input type="checkbox" class="generate-default-pages" value="help-me-relocate" checked> Help Me Relocate</label>
					</div>
          <div class="form-checkbox">
            <label><input type="checkbox" class="generate-default-pages" value="contact" checked> Contact Page</label>
          </div>
					<div class="form-checkbox">
						<label><input type="checkbox" class="generate-default-pages" value="sitemap" checked> Sitemap</label>
					</div>
					<div class="form-checkbox">
						<label><input type="checkbox" class="generate-default-pages" value="not-found" checked> 404 Page</label>
					</div>
				</div>
			</div>
		</div>
	</div>

  <div class="wpui-row wpui-row-box">
    <div class="wpui-col-md-12">
      <p>
        <span class="form-group-description"><strong>Note</strong>: To avoid content <strong>overriding</strong>, ensure <strong>customized CF7 form names</strong> are appended with <strong>(Custom)</strong> instead of (Auto-generated by AIOS Initial Setup) <strong>before generating new forms</strong>.</span>
      </p>
    </div>
  </div>

	<div class="wpui-row wpui-row-submit">
		<div class="wpui-col-md-12">
			<div class="form-group">
				<input id="generate-default-pages" type="submit" class="wpui-secondary-button text-uppercase" value="Generate Pages">
			</div>
		</div>
	</div>
</form>
