<?php

namespace AiosInitialSetup\App\Modules\ContactFormEmailTemplate;

class beforeSend
{
  use Config;

  /**
   * aios_cf7_before_send constructor.
   */
  public function __construct()
  {
    add_action('wpcf7_before_send_mail', [$this, 'aios_cf7_before_email_send']);
  }

  /**
   * @param $wpcf7
   * @return void|null
   */
  public function aios_cf7_before_email_send($wpcf7)
  {
    $options = $this->getOptions();

    $submission = \WPCF7_Submission::get_instance();
    $wpcf7 = \WPCF7_ContactForm::get_current();

    if ($submission) {
      $data = $submission->get_posted_data();
      $mail = $wpcf7->prop('mail');
      $mail2 = $wpcf7->prop('mail_2');

      if ($wpcf7->title == 'Free Home Valuation (Auto-generated by AIOS Home Valuation)') {
        return;
      }

      $aios_disable_email_templates_from = get_option('aios_disable_email_templates_from', []);
      if (!empty($aios_disable_email_templates_from) && in_array($wpcf7->id, $aios_disable_email_templates_from)) {
        return;
      }

      $c_header = '<table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="padding-top: 25px; padding-bottom: 25px;">
      <tr>
        <td align="center" valign="top">
          <table width="600" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top" bgcolor="#ffffff" style="padding-bottom: 20px; border-bottom: solid 1px #cacaca;' . $options['client_font_style'] . '">
                ' . $options['header_client'] . '
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" bgcolor="#ffffff" style="padding: 20px 0 10px;' . $options['client_font_style'] . '">
                ' . $options['intro_client'] . '
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" bgcolor="#ffffff" style="padding: 0;' . $options['client_font_style'] . '">';
      $c_footer = '</td>
            </tr>
            <tr>
              <td align="left" valign="top" bgcolor="#ffffff" style="padding: 10px 0 20px;' . $options['client_font_style'] . '">
                ' . $options['closing_client'] . '
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#ffffff" style="padding-top: 20px; border-top: solid 1px #cacaca;' . $options['client_font_style'] . '">
                ' . $options['footer_client'] . '
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>';

      $reply_to = str_replace('Reply-To: ', '', $mail['additional_headers']);
      $body = $c_header . $mail['body'] . $c_footer;
      $body = str_replace('{reply-to}', $reply_to, $body);
      $clean_body = $mail['body'];
      $mail['body'] = do_shortcode($body);
      $mail['use_html'] = 1;

      $u_header = '<table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="padding-top: 25px; padding-bottom: 25px;">
      <tr>
        <td align="center" valign="top">
          <table width="600" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top" bgcolor="#ffffff" style="padding-bottom: 20px; border-bottom: solid 1px #cacaca;' . $options['user_font_style'] . '">
                ' . $options['header_user'] . '
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" bgcolor="#ffffff" style="padding: 20px 0 10px;' . $options['user_font_style'] . '">
                ' . $options['intro_user'] . '
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" bgcolor="#ffffff" style="padding: 0;' . $options['user_font_style'] . '">';
      $u_footer = '</td>
            </tr>
            <tr>
              <td align="left" valign="top" bgcolor="#ffffff" style="padding: 10px 0 20px;' . $options['user_font_style'] . '">
                ' . $options['closing_user'] . '
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#ffffff" style="padding-top: 20px; border-top: solid 1px #cacaca;' . $options['user_font_style'] . '">
                ' . $options['footer_user'] . '
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>';

      // Auto responder value
      $responder_to = $mail2['active'] == 1 ? $mail2['recipient'] : $reply_to;
      $responder_from = $mail2['active'] == 1 ? $mail2['from'] : $mail['recipient'];
      $responder_subject = $mail2['active'] == 1 ? $mail2['subject'] : $options['opt_user_confirmation_subject'];
      $responder_body = $mail2['active'] == 1 ? $mail2['body'] : $clean_body;

      // Activate Mail2 to enable send auto responder
      if ($options['opt_user_confirmation'] !== '1') {
        $mail2['active'] = 1;
        $mail2['additional_headers'] = 'Reply-To: ' . $mail['recipient'];
        $mail2['recipient'] = do_shortcode($responder_to);
        $mail2['from'] = $responder_from;
        $mail2['subject'] = $responder_subject;
        $mail2['body'] = do_shortcode($u_header . $responder_body . $u_footer);
        $mail2['use_html'] = 1;
        $wpcf7->set_properties(["mail" => $mail, "mail_2" => $mail2]);
      } else {
        $wpcf7->set_properties(["mail" => $mail]);
      }

      return $wpcf7;
    }
  }
}

new beforeSend();
